
raw_information = {
    'Kousaka Honoka': {
        'year': 'Second',
        'sub_unit': 'Printemps',
        'cv_nickname': 'Emitsun',
        'cv_twitter': 'Nitta_Emi',
        'cv_instagram': 'Nitta_Emi',
    },
    'Nishikino Maki': {
        'year': 'First',
        'sub_unit': 'Bibi',
        'cv_nickname': 'Pile',
        'cv_twitter': 'pile_eric',
        'cv_instagram': 'pile_eric',
    },
    'Ayase Eli': {
        'year': 'Third',
        'sub_unit': 'Bibi',
        'cv_nickname': 'Nanjolno',
        'cv_twitter': 'nanjolno',
        'cv_instagram': 'nanjolno',
    },
    'Minami Kotori': {
        'year': 'Second',
        'sub_unit': 'Printemps',
        'cv_nickname': 'Ucchi',
        'cv_twitter': 'aya_uchida',
        'cv_instagram': None,
    },
    'Hoshizora Rin': {
        'year': 'First',
        'sub_unit': 'Lily White',
        'cv_nickname': 'Rippi',
        'cv_twitter': 'rippialoha',
        'cv_instagram': 'rippialoha',
    },
    'Koizumi Hanayo': {
        'year': 'First',
        'sub_unit': 'Printemps',
        'cv_nickname': 'Shikaco',
        'cv_twitter': 'shi_ka_co',
        'cv_instagram': 'shi_ka_co',
    },
    'Sonoda Umi': {
        'year': 'Second',
        'sub_unit': 'Lily White',
        'cv_nickname': 'Mimorin',
        'cv_twitter': 'mimori_suzuko',
        'cv_instagram': 'mimori_suzuko',
    },
    'Toujou Nozomi': {
        'year': 'Third',
        'sub_unit': 'Lily White',
        'cv_nickname': 'Kussun',
        'cv_twitter': 'kusudaaina',
        'cv_instagram': 'kusudaaina',
    },
    'Yazawa Nico': {
        'year': 'Third',
        'sub_unit': 'Bibi',
        'cv_nickname': 'Soramaru',
        'cv_twitter': 'tokui_sorangley',
        'cv_instagram': None,
    },
}
