
donations = [
    {
        'price': 1,
        'thanks': True,
        'col_size': 12,
    },
    {
        'price': 5,
        'thanks': True,
        'link': True,
        'col_size': 12,
    },
    {
        'price': 10,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'SUPPORTER',
        'col_size': 4,
    },
    {
        'price': 25,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'SUPPORTER',
        'keyrings': 1,
        'col_size': 3,
    },
    {
        'price': 50,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'LOVER',
        't_shirt': True,
        'col_size': 3,
    },
    {
        'price': 50,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'LOVER',
        'lovecas': 15,
        'col_size': 3,
    },
    {
        'price': 75,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'LOVER',
        'lovecas': 50,
        'col_size': 3,
    },
    {
        'price': 100,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'AMBASSADOR',
        't_shirt': True,
        'keyrings': 3,
        'col_size': 2,
    },
    {
        'price': 200,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'AMBASSADOR',
        't_shirt': True,
        'keyrings': 5,
        'box': True,
        'col_size': 2,
    },
    {
        'price': 500,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'PRODUCER',
        't_shirt': True,
        'feature': True,
        'keyrings': 9,
        'homepage_link': True,
        'col_size': 2,
    },
    {
        'price': 500,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'PRODUCER',
        't_shirt': True,
        'keyrings': 5,
        'box': True,
        'homepage_link': True,
        'col_size': 2,
    },
    {
        'price': 800,
        'thanks': True,
        'link': True,
        'postcard': True,
        'status': 'DEVOTEE',
        't_shirt': True,
        'keyrings': 9,
        'homepage_link': True,
        'homepage_character': True,
        'col_size': 2,
    },
]
