from collections import OrderedDict

archive = OrderedDict([
    (2020, [
        {
            'username': u'db0',
            'idol_name': u'Asaka Karin',
            'image': u'https://i.imgur.com/z3OE3oJ.png',
            'winners_id': 10418436,
            'tag': u'KarinFanAwards2020',
            'id': 10418208,
        },
        {
            'username': u'db0',
            'idol_name': u'Ohara Mari',
            'image': u'https://i.imgur.com/BsK5maS.png',
            'winners_id': 10418106,
            'tag': u'MariFanAwards2020',
            'id': 10417945,
        },
        {
            'username': u'db0',
            'idol_name': u'Toujou Nozomi',
            'image': u'https://i.imgur.com/m9qNxLv.png',
            'winners_id': 10418058,
            'tag': u'NozomiFanAwards2020',
            'id': 10417816,
        },
        {
            'username': u'db0',
            'idol_name': u'Miyashita Ai',
            'image': u'https://i.imgur.com/hxG0ggo.png',
            'winners_id': None,
            'tag': u'AiFanAwards2020',
            'id': 10417855,
        },
        {
            'username': u'db0',
            'idol_name': u'Nishikino Maki',
            'image': u'https://i.imgur.com/UkwuSn7.png',
            'winners_id': 10416678,
            'tag': u'MakiFanAwards2020',
            'id': 10416162,
        },
        {
            'username': u'db0',
            'idol_name': u'Watanabe You',
            'image': u'https://i.imgur.com/1HwlsAy.png',
            'winners_id': 10416336,
            'tag': u'YouFanAwards2020',
            'id': 10416099,
        },
        {
            'username': u'db0',
            'idol_name': u'Sonoda Umi',
            'image': u'https://i.imgur.com/SEpXED7.png',
            'winners_id': 10415373,
            'tag': u'UmiFanAwards2020',
            'id': 10415220,
        },
        {
            'username': u'db0',
            'idol_name': u'Kunikida Hanamaru',
            'image': u'https://i.imgur.com/lC5spOR.png',
            'winners_id': 10415130,
            'tag': u'HanamaruFanAwards2020',
            'id': 10414960,
        },
        {
            'username': u'db0',
            'idol_name': u'Uehara Ayumu',
            'image': u'https://i.imgur.com/T0i0GgQ.png',
            'winners_id': 10415039,
            'tag': u'AyumuFanAwards2020',
            'id': 10414899,
        },
        {
            'username': u'db0',
            'idol_name': u'Matsuura Kanan',
            'image': u'https://i.imgur.com/MH0kqRB.png',
            'winners_id': 10414634,
            'tag': u'KananFanAwards2020',
            'id': 10414437,
        },
        {
            'username': u'db0',
            'idol_name': u'Emma Verde',
            'image': u'https://i.imgur.com/Z2kGEEC.png',
            'winners_id': 10414559,
            'tag': u'EmmaFanAwards2020',
            'id': 10414334,
        },
        {
            'username': u'db0',
            'idol_name': u'Nakasu Kasumi',
            'image': u'https://i.imgur.com/YSjJb1s.jpg',
            'winners_id': 10414182,
            'tag': u'KasumiFanAwards2020',
            'id': 10414041,
        },
        {
            'username': u'db0',
            'idol_name': u'Koizumi Hanayo',
            'image': u'https://i.imgur.com/P3QGOyF.png',
            'winners_id': 10414083,
            'tag': u'HanayoFanAwards2020',
            'id': 10413913,
        },
        {
            'username': u'db0',
            'idol_name': u'Kurosawa Dia',
            'image': u'https://i.imgur.com/kItkGvI.png',
            'winners_id': 10413759,
            'tag': u'DiaFanAwards2020',
            'id': 10413645,
        },
    ]),
    (2019, [
        {
            'username': u'db0',
            'idol_name': u'Konoe Kanata',
            'image': u'https://i.imgur.com/MAox4b3.png',
            'winners_id': 10413480,
            'tag': u'KanataFanAwards2019',
            'id': 10413395,
        },
        {
            'username': u'db0',
            'idol_name': u'Tennoji Rina',
            'image': u'https://i.imgur.com/HqFHkzP.png',
            'winners_id': 10412604,
            'tag': u'RinaFanAwards2019',
            'id': 10412348,
        },
        {
            'username': u'db0',
            'idol_name': u'Hoshizora Rin',
            'image': u'https://i.imgur.com/CW9Sm9p.png',
            'winners_id': 10412392,
            'tag': u'RinFanAwards2019',
            'id': 10411986,
        },
        {
            'username': u'db0',
            'idol_name': u'Ayase Eli',
            'image': u'https://i.imgur.com/2eyTcuE.png',
            'winners_id': 10412097,
            'tag': u'EliFanAwards2019',
            'id': 10411686,
        },
        {
            'username': u'db0',
            'idol_name': u'Kurosawa Ruby',
            'image': u'https://i.imgur.com/K5jhUlo.png',
            'winners_id': 10411199,
            'tag': u'RubyFanAwards2019',
            'id': 10410723,
        },
        {
            'username': u'db0',
            'idol_name': u'Sakurauchi Riko',
            'image': u'https://i.imgur.com/zYxPUIa.png',
            'winners_id': 10411199,
            'tag': u'RikoFanAwards2019',
            'id': 10410654,
        },
        {
            'username': u'db0',
            'idol_name': u'Minami Kotori',
            'image': u'https://i.imgur.com/RhQKSnf.png',
            'winners_id': 10410883,
            'tag': u'KotoriFanAwards2019',
            'id': 10410386,
        },
        {
            'username': u'db0',
            'idol_name': u'Yuki Setsuna',
            'image': u'https://i.imgur.com/0eQ4rk7.png',
            'winners_id': 10409477,
            'tag': u'SetsunaFanAwards2019',
            'id': 10409297,
        },
        {
            'username': u'db0',
            'idol_name': u'Kousaka Honoka',
            'image': u'https://i.imgur.com/yX2Teu1.png',
            'winners_id': 10409453,
            'tag': u'HonokaFanAwards2019',
            'id': 10409104,
        },
        {
            'username': u'db0',
            'idol_name': u'Takami Chika',
            'image': u'https://i.imgur.com/eMUjN1n.png',
            'winners_id': 10409453,
            'tag': u'ChikaFanAwards2019',
            'id': 10409024,
        },
        {
            'username': u'db0',
            'idol_name': u'Yazawa Nico',
            'image': u'https://i.imgur.com/mFyt6PE.png',
            'winners_id': 10409086,
            'tag': u'NicoFanAwards2019',
            'id': 10408817,
        },
        {
            'username': u'db0',
            'idol_name': u'Asaka Karin',
            'image': u'https://i.imgur.com/z3OE3oJ.png',
            'winners_id': 10408436,
            'tag': u'KarinFanAwards2019',
            'id': 10408291,
        },
        {
            'username': u'db0',
            'idol_name': u'Ohara Mari',
            'image': u'https://i.imgur.com/BsK5maS.png',
            'winners_id': 10408043,
            'tag': u'MariFanAwards2019',
            'id': 10407908,
        },
        {
            'username': u'db0',
            'idol_name': u'Toujou Nozomi',
            'image': u'https://i.imgur.com/m9qNxLv.png',
            'winners_id': 10408043,
            'tag': u'NozomiFanAwards2019',
            'id': 10407767,
        },
        {
            'username': u'db0',
            'idol_name': u'Miyashita Ai',
            'image': u'https://i.imgur.com/hxG0ggo.png',
            'winners_id': 10407741,
            'tag': u'AiFanAwards2019',
            'id': 10407454,
        },
        {
            'username': u'db0',
            'idol_name': u'Nishikino Maki',
            'image': u'https://i.imgur.com/jrlFXaZ.png',
            'winners_id': 10406713,
            'tag': u'MakiFanAwards2019',
            'id': 10406468,
        },
        {
            'username': u'db0',
            'idol_name': u'Watanabe You',
            'image': u'https://i.imgur.com/JFjivDM.png',
            'winners_id': 10406712,
            'tag': u'YouFanAwards2019',
            'id': 10406415,
        },
        {
            'username': u'db0',
            'idol_name': u'Sonoda Umi',
            'image': u'https://i.imgur.com/mVFxajV.png',
            'winners_id': 10405705,
            'tag': u'UmiFanAwards2019',
            'id': 10405318,
        },
        {
            'username': u'db0',
            'idol_name': u'Kunikida Hanamaru',
            'image': u'https://i.imgur.com/NBWs3W0.png',
            'winners_id': 10405636,
            'tag': u'HanamaruFanAwards2019',
            'id': 10400953,
        },
        {
            'username': u'db0',
            'idol_name': u'Uehara Ayumu',
            'image': u'https://i.imgur.com/XuwbKOq.png',
            'winners_id': 10405251,
            'tag': u'AyumuFanAwards2019',
            'id': 10389070,
        },
        {
            'username': u'db0',
            'idol_name': u'Matsuura Kanan',
            'image': u'https://i.imgur.com/ATOaf5Z.png',
            'winners_id': 10368777,
            'tag': u'KananFanAwards2019',
            'id': 10301013,
        },
        {
            'username': u'db0',
            'idol_name': u'Kurosawa Dia',
            'image': u'https://i.imgur.com/yKc1SCc.png',
            'winners_id': 10180821,
            'tag': u'DiaBirthdayGiveaway2019',
            'id': 10110039,
        },
        {
            'username': u'db0',
            'idol_name': 'Yohane',
            'image': u'https://i.imgur.com/isNtjPE.png',
            'winners_id': 10408888,
            'tag': u'YohaneFanAwards2019',
            'id': 10408639,
        },
        {
            'id': 10278151,
            'idol_name': u'Emma Verde',
            'image': u'https://i.imgur.com/z2dZ5xk.png',
            'tag': 'EmmaFanElection2019',
            'total_participants': 5,
            'username': u'db0',
            'winners_id': 10326472,
        },
        {
            'id': 10216795,
            'idol_name': u'Nakasu Kasumi',
            'image': u'https://i.imgur.com/FwSY6GP.png',
            'tag': 'KasumiFanElection2019',
            'total_participants': 6,
            'username': u'db0',
            'winners_id': 10241347,
        },
        {
            'id': 10186480,
            'idol_name': u'Koizumi Hanayo',
            'image': u'https://i.imgur.com/9Raihox.png',
            'tag': 'HanayoFanElection2019',
            'total_participants': 20,
            'username': u'db0',
            'winners_id': 10251780,
        },
    ]),
    (2018, [
        {
            'username': u'db0',
            'idol_name': u'Konoe Kanata',
            'image': u'https://i.imgur.com/7sG6VBW.png',
            'winners_id': 10054531,
            'tag': u'KanataBirthdayGiveaway2018',
            'id': 10023793,
        },
        {
            'username': u'db0',
            'idol_name': u'Tennoji Rina',
            'image': u'https://i.imgur.com/6Nv93tm.png',
            'winners_id': 9844747,
            'tag': u'RinaBirthdayGiveaway2018',
            'id': 9727532,
        },
        {
            'username': u'db0',
            'idol_name': u'Hoshizora Rin',
            'image': u'https://i.imgur.com/BMf4Ted.png',
            'winners_id': 9745329,
            'tag': u'RinBirthdayGiveaway2018',
            'id': 9665075,
        },
        {
            'username': u'db0',
            'idol_name': u'Ayase Eli',
            'image': u'https://i.imgur.com/py9KWh7.png',
            'winners_id': 9694644,
            'tag': u'EliBirthdayGiveaway2018',
            'id': 9607369,
        },
        {
            'username': u'db0',
            'idol_name': u'Kurosawa Ruby',
            'image': u'https://i.imgur.com/wJpNbpx.png',
            'winners_id': 9535956,
            'tag': u'RubyBirthdayGiveaway2018',
            'id': 9452251,
        },
        {
            'username': u'db0',
            'idol_name': u'Sakurauchi Riko',
            'image': u'https://i.imgur.com/poOaLDH.png',
            'winners_id': 9520623,
            'tag': u'RikoBirthdayGiveaway2018',
            'id': 9441844,
        },
        {
            'username': u'db0',
            'idol_name': u'Minami Kotori',
            'image': u'https://i.imgur.com/k8R3q6r.jpg',
            'winners_id': 9486734,
            'tag': u'KotoriBirthdayGiveaway2018',
            'id': 9404817,
        },
        {
            'username': u'db0',
            'idol_name': u'Kousaka Honoka',
            'image': u'https://i.imgur.com/NlsiE9b.png',
            'winners_id': 6843963,
            'tag': u'HonokaBirthdayGiveaway2018',
            'id': 9160933,
        },
        {
            'username': u'db0',
            'idol_name': u'Takami Chika',
            'image': u'https://i.imgur.com/FhgPBOU.png',
            'winners_id': 6843947,
            'tag': u'ChikaBirthdayGiveaway2018',
            'id': 9136624,
        },
        {
            'username': u'db0',
            'idol_name': u'Yazawa Nico',
            'image': u'https://i.imgur.com/YMfwdme.png',
            'winners_id': 6579586,
            'tag': u'NicoBirthdayGiveaway2018',
            'id': 9077504,
        },
        {
            'username': u'db0',
            'idol_name': u'Ohara Mari',
            'image': u'https://i.imgur.com/wfOImqi.jpg',
            'winners_id': 8939069,
            'tag': u'MariBirthdayGiveaway2018',
            'id': 8855538,
        },
        {
            'username': u'db0',
            'idol_name': u'Toujou Nozomi',
            'image': u'https://i.imgur.com/9enkqjm.jpg',
            'winners_id': 8925456,
            'tag': u'NozomiBirthdayGiveaway2018',
            'id': 8841314,
        },
        {
            'username': u'Hikari_Dragneel',
            'idol_name': u'Nishikino Maki',
            'image': u'https://i.imgur.com/UIZbSDq.png',
            'winners_id': 8576555,
            'tag': u'MakiBirthdayGiveaway2018',
            'id': 8474387,
        },
        {
            'username': u'Hikari_Dragneel',
            'idol_name': u'Watanabe You',
            'image': u'https://i.imgur.com/bvQ0bJ4.png',
            'winners_id': 8576586,
            'tag': u'YouBirthdayGiveaway2018',
            'id': 8449681,
        },
        {
            'username': u'db0',
            'idol_name': 'Yohane',
            'image': u'https://i.imgur.com/Az8Ml52.png',
            'winners_id': 9117725,
            'tag': u'YohaneBirthdayGiveaway2018',
            'id': 9024133,
        },
    ]),
    ('',
     [{
         'username': u'db0',
         'idol_name': u'Konoe Kanata',
         'image': u'https://pbs.twimg.com/media/DRITAMbUMAAkUQw.jpg',
         'winners_id': 10054531,
         'tag': u'KanataBirthdayGiveaway',
         'id': 7612872,
     },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Hoshizora Rin',
          'image': u'https://i.imgur.com/t3e8xeY.jpg',
          'winners_id': 9745329,
          'tag': 'RinBirthdayGiveaway',
          'id': 7287840,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Ayase Eli',
          'image': u'https://i.imgur.com/65aSMt3.jpg',
          'winners_id': 9694644,
          'tag': 'EliBirthdayGiveaway',
          'id': 7192703,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Kurosawa Ruby',
          'image': u'https://i.imgur.com/5rMGu4t.png',
          'winners_id': 9535956,
          'tag': 'RubyBirthdayGiveaway',
          'id': 6963896,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Sakurauchi Riko',
          'image': u'http://i68.tinypic.com/f3wcn9.jpg',
          'winners_id': 9520623,
          'tag': 'RikoBirthdayGiveaway',
          'id': 6952568,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Minami Kotori',
          'image': u'https://i.imgur.com/OngQiho.jpg',
          'winners_id': 9486734,
          'tag': 'KotoriBirthdayGiveaway',
          'id': 6885593,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Kousaka Honoka',
          'image': u'http://i.imgur.com/06v3HuF.png',
          'winners_id': 6843963,
          'tag': 'HonokaBirthdayGiveaway',
          'id': 6542796,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Takami Chika',
          'image': u'http://i.imgur.com/pApldos.png',
          'winners_id': 6843947,
          'tag': 'ChikaBirthdayGiveaway',
          'id': 6523113,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Yazawa Nico',
          'image': u'http://i.imgur.com/tonpkXJ.png',
          'winners_id': 6579586,
          'tag': 'NicoBirthdayGiveaway',
          'id': 6441152,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Tsushima Yoshiko',
          'image': u'http://i.imgur.com/msmg7re.png',
          'winners_id': None,
          'tag': 'YoshikoBirthdayGiveaway',
          'id': 6365720,
      },
      {
          'username': u'ryuko',
          'idol_name': u'Ohara Mari',
          'image': u'https://cdn.discordapp.com/attachments/269848996363632641/323909910402170900/maribday.png',
          'winners_id': 6279691,
          'tag': 'MariBirthdayGiveaway',
          'id': 6156072,
      },
      {
          'username': u'ryuko',
          'idol_name': u'Toujou Nozomi',
          'image': u'http://i.imgur.com/gqSExKn.png',
          'winners_id': 6279624,
          'tag': 'NozomiBirthdayGiveaway',
          'id': 6120956,
      },
      {
          'username': u'db0',
          'idol_name': u'Nishikino Maki',
          'image': u'http://i.imgur.com/YbAqslD.jpg',
          'winners_id': 8576555,
          'tag': u'MakiBirthdayGiveaway',
          'id': 5672699,
      },
      {
          'username': u'db0',
          'idol_name': u'Watanabe You',
          'image': u'http://i.imgur.com/0sZ8dvp.jpg',
          'winners_id': 8576586,
          'tag': u'YouBirthdayGiveaway',
          'id': 5642070,
      },
      {
          'username': u'db0',
          'idol_name': u'Sonoda Umi',
          'image': u'https://i.imgur.com/38lUkas.png',
          'winners_id': 8240893,
          'tag': u'UmiBirthdayGiveaway',
          'id': 8240893,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Kunikida Hanamaru',
          'image': u'https://i.imgur.com/q5gyflu.jpg',
          'winners_id': 8274515,
          'tag': u'HanamaruBirthdayGiveaway',
          'id': 8169626,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Uehara Ayumu',
          'image': u'https://i.imgur.com/uROAIVH.png',
          'winners_id': 8260064,
          'tag': 'AyumuBirthdayGiveaway',
          'id': 8156179,
      },
      {
          'username': u'db0',
          'idol_name': u'Matsuura Kanan',
          'image': u'https://i.imgur.com/M2QBQPy.png',
          'winners_id': 8146816,
          'tag': u'KananBirthdayGiveaway',
          'id': 8036303,
      },
      {
          'username': u'Hikari_Dragneel',
          'idol_name': u'Emma Verde',
          'image': u'https://i.imgur.com/omnTLTY.png',
          'winners_id': 8169737,
          'tag': 'EmmaBirthdayGiveaway',
          'id': 8007292,
      },
      {
          'username': u'db0',
          'idol_name': u'Koizumi Hanayo',
          'image': u'https://i.imgur.com/uP2UPt3.png',
          'winners_id': 7987650,
          'tag': u'HanayoBirthdayGiveaway',
          'id': 7873132,
      },
      {
          'username': u'db0',
          'idol_name': u'Kurosawa Dia',
          'image': u'https://i.imgur.com/RcyQ9IC.png',
          'winners_id': 10180821,
          'tag': u'DiaBirthdayGiveaway',
          'id': 7750271,
      },
     ]),
])

has_not_been_organized = []
