# -*- coding: utf-8 -*-

def get_links(current_en, current_jp):
    return [
        {
            'name': 'Download',
            'link': 'download',
            'idol': 'Kousaka Honoka',
            'links': [
                {
                    'name': 'iOs: English Version',
                    'url': 'https://itunes.apple.com/us/app/school-idol-festival/id834030294?mt=8',
                    'language': 'english',
                },
                {
                    'name': 'iOs: Japanese Version',
                    'url': 'https://itunes.apple.com/jp/app/raburaibu!sukuruaidorufesutibaru/id626776655?mt=8',
                    'language': 'japanese',
                },
                {
                    'name': 'iOs: Guide to install Japanese games',
                    'description': 'Follow this tutorial if you couldn\'t download the Japanese game on your iPhone.',
                    'url': 'http://2p.com/4161143_1/Wanna-Register-for-a-Japanese-iTunes-Account-This-Guide-Teaches-U-How-to-Creat-by-yuko',
                    'type': 'tutorial',
                    'language': 'japanese',
                },
                {
                    'name': 'Android: English Version',
                    'url': 'https://play.google.com/store/apps/details?id=klb.android.lovelive_en',
                    'language': 'english',
                },
                {
                    'name': 'Android: Japanese Version',
                    'url': 'https://play.google.com/store/apps/details?id=klb.android.lovelive&hl=en',
                    'language': 'japanese',
                },
                {
                    'name': 'APKs and Links',
                    'description': 'If none of the Android links worked, that\'s what you\'re searching for.',
                    'url': 'http://platinumdis.co/lovelive',
                    'language': 'world',
                },
                {
                    'name': 'Android APKs',
                    'description': 'Another mirrors to download the APKs directly.',
                    'url': 'https://ll.idolactiviti.es/apk/',
                    'language': 'world',
                },
                {
                    'name': 'Play on a rooted Android',
                    'description': '"Illegal access detected!"? Here is the solution.',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/wiki/rooting',
                    'type': 'tutorial',
                    'language': 'world',
                },
            ],
        },
        {
            'name': 'Get Started',
            'link': 'getstarted',
            'idol': 'Yazawa Nico',
            'links': [
                {
                    'name': 'Beginner\'s guide',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/wiki/guide',
                    'x2': True,
                    'type': 'tutorial',
                    'language': 'world',
                },
                {
                    'name': 'Menu\'s Translation',
                    'description': 'Useful if you play on the Japanese version.',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Menus',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'GamePlay',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Gameplay',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'Frequently Asked Questions',
                    'description': 'Reddit Version.',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/wiki/faq',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'Frequently Asked Questions',
                    'description': 'Decaf Wiki Version.',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=FAQ',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'List of Items',
                    'description': 'In game points and virtual money.',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Items',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'Save your Transfer Code',
                    'description': 'First thing to do! In case you loose your device, it will allow you to retrieve your precious account.',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/wiki/passcode',
                    'type': 'tutorial',
                    'language': 'world',
                },
            ],
        },
        {
            'name': 'News & Updates',
            'link': 'tutorials',
            'idol': 'Ayase Eli',
            'links': [
                {
                    'name': 'Facebook Page',
                    'url': 'https://www.facebook.com/schoolidolfestival',
                    'description': 'Official page with news about the game.',
                    'type': '',
                    'language': 'english',
                },
                {
                    'name': 'Twitter @LLSIF_english',
                    'url': 'https://twitter.com/LLSIF_english',
                    'type': '',
                    'language': 'english',
                },
                {
                    'name': 'Official Twitter @lovelive_staff',
                    'url': 'https://twitter.com/lovelive_staff',
                    'type': '',
                    'language': 'japanese',
                },
                {
                    'name': 'Twitter @lovelivemuse',
                    'url': 'https://twitter.com/lovelivemuse',
                    'type': '',
                    'language': 'english',
                },
                {
                    'name': 'Twitter @loveliveconfess',
                    'url': 'https://twitter.com/loveliveconfess',
                    'type': '',
                    'language': 'english',
                },
                {
                    'name': 'English In Game Updates',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=English_Version_Info',
                    'type': 'info',
                    'language': 'english',
                },
                {
                    'name': 'Japanese In Game Updates',
                    'description': 'Translated in English.',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Updates',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Official News about LoveLive! Franchise',
                    'url': 'http://news.lovelive-anime.jp/app-def/S-102/news/',
                    'language': 'japanese',
                    'type': 'info',
                },
            ],
        },
        {
            'name': 'Communities',
            'link': 'communities',
            'idol': 'Toujou Nozomi',
            'links': [
                {
                    'name': 'Reddit',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/',
                    'x2': True,
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': '4Chan',
                    'url': 'http://boards.4chan.org/vg/catalog',
                    'description': 'Type ctrl+F \'love live\' to get the current thread.',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'Facebook Group',
                    'url': 'https://www.facebook.com/groups/293090280852174/',
                    'description': 'Mainly casual gamers but very active community.',
                    'x2': True,
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'School Idol Tomodachi',
                    'description': 'Discuss with players using comments on their pages.',
                    'url': '/users/',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'AnimeSuki Forum',
                    'url': 'http://forums.animesuki.com/showthread.php?t=126816',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'Crunchyroll Forum',
                    'url': 'http://www.crunchyroll.com/forumtopic-855485/love-live-school-idol-festival-app-game?pg=0',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'MyAnimeList Forum',
                    'url': 'http://myanimelist.net/forum/?topicid=635035',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'Fuwanovel Forum',
                    'url': 'http://forums.fuwanovel.org/index.php?/topic/5034-love-live-school-idol-festival-thread/',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'NeoGAF Forum',
                    'url': 'http://www.neogaf.com/forum/showthread.php?t=817534',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'Hummingbird Forum',
                    'url': 'http://forums.hummingbird.me/t/love-live-school-idol-ios-and-android/9088',
                    'type': '',
                    'language': 'world',
                },
            ],
        },
        {
            'name': 'Collect Cards',
            'link': 'cards',
            'idol': 'Koizumi Hanayo',
            'links': [
                {
                    'name': 'Browse Cards',
                    'description': 'Search for cards using smart filters and ordering.',
                    'url': '/cards',
                    'type': 'info',
                    'language': 'world',
                    'x2': True,
                },
                {
                    'name': 'Track your Cards',
                    'url': '/cards',
                    'description': 'Helps you fill your album in the game - and brag about your cards ;)',
                    'type': 'tool',
                    'language': 'world',
                },
                {
                    'name': 'Vote for the BEST girl',
                    'url': '/contest',
                    'description': 'Vote for your favorite cards on School Idol Contest, the Facemash.',
                    'x2': True,
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'Recruitment Simulator',
                    'url': 'http://scfes.mnyk.info/',
                    'type': 'tool',
                    'language': 'japanese',
                },
                {
                    'name': 'Cards you can get from songs',
                    'url': 'http://xn--eck5eb7eb.gamerch.com/%E3%83%A9%E3%82%A4%E3%83%96%E5%A0%B1%E9%85%AC',
                    'description': 'Sometimes you can get an R at the end of some songs.',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'Trade Accounts on Facebook',
                    'url': 'https://www.facebook.com/groups/348965238597534/',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'Trade Accounts on Reddit',
                    'url': 'http://www.reddit.com/r/SIFTrades',
                    'type': '',
                    'language': 'world',
                },
                {
                    'name': 'Experience required to level up a card',
                    'url': 'http://www59.atwiki.jp/lovelive-sif/pages/32.html',
                    'type': 'info',
                    'language': 'world',
                },
            ],
        },
        {
            'name': 'Play Songs',
            'link': 'songs',
            'idol': 'Nishikino Maki',
            'links': [
                {
                    'name': 'Scoring Guide',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Scoring',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'List of songs',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Songs',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'Android Traning App Sukutore',
                    'description': 'Train your fingers without wasting your LPs!',
                    'url': 'https://play.google.com/store/apps/details?id=siy.sukutore&hl=en',
                    'x2': True,
                    'type': 'tool',
                    'language': 'world',
                },
                {
                    'name': 'Assist Guides for each songs',
                    'url': 'https://www.youtube.com/user/OktopazOfficial',
                    'description': 'Songs are slowed down, showed with and without hands, with a beatmania-like representation and good sound feedback.',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'List of songs ordered by length',
                    'description': 'Type ctrl+F \'#スクフェス\'. ✩  means special song, 日 means daily song.',
                    'url': 'https://twitter.com/haku_kuten',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'How to Create the Perfect Team',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/comments/2pg7ap/basic_guide_creating_the_perfect_team/',
                    'type': 'tutorial',
                    'language': 'world',
                },
                {
                    'name': 'Advanced Scoring Guide',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/comments/2r5nx6/guide_advanced_scoring_guide/',
                    'type': 'tutorial',
                    'language': 'world',
                },
            ],
        },
        {
            'name': 'Join Events',
            'link': 'events',
            'idol': 'Minami Kotori',
            'links': [
                {
                    'name': 'Types of Events & How to Play',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Gameplay#Events',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': ('Current' if current_en.is_world_current() else 'Latest') + ' Event English Version',
                    'description': current_en.english_name,
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=' + current_en.japanese_name,
                    'x2': True,
                    'type': 'info',
                    'language': 'english',
                },
                {
                    'name': ('Current' if current_en.is_japan_current() else 'Latest') + ' Event Japanese Version',
                    'description': current_jp.japanese_name,
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=' + current_jp.japanese_name,
                    'x2': True,
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'English Event Tracker',
                    'description': 'Track statistics about the current English event.',
                    'url': 'https://sites.google.com/site/llsifeneventtracker/',
                    'type': 'info',
                    'language': 'english',
                },
                {
                    'name': 'Japanese Event Tracker',
                    'description': 'Track statistics about the current Japanese event.',
                    'url': 'http://atsites.jp/llborder/',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Events Rank Calculator',
                    'url': 'https://yefta.com/llsif/',
                    'description': 'A tool to calculate the required loveca and time you will need to get a certain position in the global ranking.',
                    'x2': True,
                    'type': 'tool',
                    'language': 'world',
                },
                {
                    'name': 'Japanese Events Tier 2 Cutoff Predictor',
                    'url': 'http://www.usagi.org/doi-bin/llcutoff.pl',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Regular Events: Efficient Token Collection',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/comments/2hylbz/basic_guide_efficient_token_collection/',
                    'type': 'tutorial',
                    'language': 'world',
                },
                {
                    'name': 'Score Match Events: Efficient Playing',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/comments/2hylze/basic_guide_efficient_score_match/',
                    'type': 'tutorial',
                    'language': 'world',
                },
                {
                    'name': 'How to spend your lovecas during events (and why)',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/comments/2fvm3y/advanced_guide_making_the_most_out_of_events/',
                    'type': 'tutorial',
                    'language': 'world',
                },
                {
                    'name': 'Event Cards',
                    'url': '/cards/?is_event=on&ordering=release_date&reverse_order=on',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'List Of Past Events',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=List_of_Events',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'Reddit Hall Of Fame',
                    'description': 'English Version previous winners on Reddit.',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/wiki/ranks',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'Previous events rankings',
                    'url': 'https://ll.idolactiviti.es/',
                    'type': 'info',
                    'language': 'english',
                }
            ],
        },
        {
            'name': 'Read Stories',
            'link': 'stories',
            'idol': 'Sonoda Umi',
            'links': [
                {
                    'name': 'Main Story Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Story',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Kousaka Honoka Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Kousaka Honoka#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Sonoda Umi Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Sonoda Umi#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Minami Kotori Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Minami Kotori#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Hoshizora Rin Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Hoshizora Rin#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Nishikino Maki Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Nishikino Maki#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Koizumi Hanayo Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Koizumi Hanayo#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Yazawa Nico Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Yazawa Nico#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Ayase Eli Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Ayase Eli#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Toujou Nozomi Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Toujou Nozomi#Side_Stories',
                    'type': 'info',
                    'language': 'japanese',
                },
                {
                    'name': 'Other Characters (N) Side Stories Translation',
                    'url': 'http://decaf.kouhi.me/lovelive/index.php?title=Category:Other_Characters',
                    'type': 'info',
                    'language': 'japanese',
                },
            ],
        },
        {
            'name': 'More',
            'link': 'other',
            'idol': 'Hoshizora Rin',
            'links': [
                {
                    'name': 'Points required to rank up',
                    'url': 'http://www59.atwiki.jp/lovelive-sif/pages/23.html',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'How to predict the future?',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/comments/2eqp2y/advanced_guide_how_to_predict_future_releases_and/',
                    'type': 'tutorial',
                    'language': 'world',
                },
                {
                    'name': 'Start a new account',
                    'description': 'This guide for players who already know the game basics. Otherwise, read the guides for beginners instead.',
                    'url': 'http://www.reddit.com/r/SchoolIdolFestival/comments/2elxb5/advanced_guide_starting_a_new_account_for_en_and/',
                    'type': 'tutorial',
                    'language': 'world',
                },
                {
                    'name': 'Play on a PC',
                    'url': 'http://pastebin.com/gx0a1mEY',
                    'type': 'tutorial',
                    'language': 'world',
                },
                {},
                {
                    'name': 'Information about the anime',
                    'url': 'http://myanimelist.net/anime/15051/Love_Live!_School_Idol_Project',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'General Wiki about LoveLive!',
                    'url': 'http://love-live.wikia.com/wiki/Main_Page',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'LoveLive! Discography',
                    'url': 'http://love-live.wikia.com/wiki/Category:Discography',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'LoveLive! The Manga',
                    'url': 'http://love-live.wikia.com/wiki/Love_Live!_School_idol_project_(Manga)',
                    'type': 'info',
                    'language': 'world',
                },
                {
                    'name': 'LoveLive! School Idol Paradise',
                    'description': 'PS Vita Game',
                    'url': 'http://love-live.wikia.com/wiki/Love_Live!_School_idol_paradise',
                    'type': 'info',
                    'language': 'world',
                },
            ],
        },
    ]
